/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Patient;

import Business.Business;
import Business.FinancialAccount.Insurance;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vaibhav
 */
public class ManageAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountJPanel
     */
    private JPanel workContainer;
    private UserAccount userAccount;
    private Business business;
    
    public ManageAccountJPanel(JPanel workContainer,UserAccount userAccount,Business business) {
        initComponents();
        this.business = business;
        this.workContainer = workContainer;
        this.userAccount = userAccount;
        populatetheTextFields();
       
        insurerjComboBox.setVisible(false);
        updatedCoveredAmountjTextField.setVisible(false);
        insurerjLabel.setVisible(false);
        coveredAmountjLabel.setVisible(false);
    }
    
    private void populatetheTextFields(){
        
        Patient patient = (Patient)userAccount.getPerson();
        if(patient.getPatientFinancialAccount() != null)
        {
            currentBalancejTextField.setText(String.valueOf(patient.getPatientFinancialAccount().getTotalBalance()));
            if(patient.getPatientFinancialAccount().getInsurance() != null)
            {
                insurerjTextField.setText(String.valueOf(patient.getPatientFinancialAccount().getInsurance().getName()));
                coveredAmountjTextField.setText(String.valueOf(patient.getPatientFinancialAccount().getCoveredAmount()));
                
            }
            else
            {
               insurerjTextField.setText("Not Insured");
                coveredAmountjTextField.setText("Not Insured"); 
            }
            
        }
        
    }
    
     private void populateInsurerJCombo(){
        
        insurerjComboBox.removeAllItems();
        
        for(Insurance company: business.getInsuranceCompanyList())
        {
            if(company != null)
            insurerjComboBox.addItem(company);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentBalancejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        insurerjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        coveredAmountjTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balancejTextField = new javax.swing.JTextField();
        insurerjLabel = new javax.swing.JLabel();
        insurerjComboBox = new javax.swing.JComboBox();
        coveredAmountjLabel = new javax.swing.JLabel();
        updatedCoveredAmountjTextField = new javax.swing.JTextField();
        updatejButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        yesjRadioButton = new javax.swing.JRadioButton();
        nojRadioButton = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Account");

        jLabel2.setText("Current Balance:");

        currentBalancejTextField.setEnabled(false);

        jLabel3.setText("Insurer:");

        insurerjTextField.setEnabled(false);

        jLabel4.setText("Covered Amount:");

        coveredAmountjTextField.setEnabled(false);

        jLabel5.setText("Update Details:");

        jLabel6.setText("Balance:");

        insurerjLabel.setText("Insurer:");

        insurerjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        coveredAmountjLabel.setText("Covered Amount:");

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });

        jLabel9.setText("Insured:");

        buttonGroup1.add(yesjRadioButton);
        yesjRadioButton.setText("Yes");
        yesjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesjRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nojRadioButton);
        nojRadioButton.setText("No");
        nojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nojRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(currentBalancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(insurerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(coveredAmountjTextField)))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yesjRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nojRadioButton))
                                    .addComponent(balancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updatejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coveredAmountjLabel)
                                    .addComponent(insurerjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updatedCoveredAmountjTextField)
                                    .addComponent(insurerjComboBox, 0, 184, Short.MAX_VALUE))))
                        .addGap(363, 363, 363))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentBalancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insurerjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(coveredAmountjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(balancejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yesjRadioButton)
                    .addComponent(nojRadioButton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insurerjLabel)
                    .addComponent(insurerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(coveredAmountjLabel)
                    .addComponent(updatedCoveredAmountjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(updatejButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
        // TODO add your handling code here:
        try{
              Patient patient = (Patient)userAccount.getPerson();
            Double balance = Double.parseDouble(balancejTextField.getText());
            if(insurerjComboBox.isVisible() && coveredAmountjTextField.isVisible())
            { Double coveredAmount = Double.parseDouble(updatedCoveredAmountjTextField.getText());
        Insurance company = (Insurance)insurerjComboBox.getSelectedItem();
            patient.getPatientFinancialAccount().setInsurance(company);
            patient.getPatientFinancialAccount().setCoveredAmount(coveredAmount);
            }
            
        
        patient.getPatientFinancialAccount().setTotalBalance(balance);
        
        populatetheTextFields();
          JOptionPane.showMessageDialog(null, "Account Updated");
           
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter numeric values");
            return;
        }
        
        
        
    }//GEN-LAST:event_updatejButtonActionPerformed

    private void yesjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesjRadioButtonActionPerformed
        // TODO add your handling code here:
        insurerjComboBox.setVisible(true);
        updatedCoveredAmountjTextField.setVisible(true);
        insurerjLabel.setVisible(true);
        coveredAmountjLabel.setVisible(true);
        populateInsurerJCombo();
        
    }//GEN-LAST:event_yesjRadioButtonActionPerformed

    private void nojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nojRadioButtonActionPerformed
        // TODO add your handling code here:
        insurerjComboBox.setVisible(false);
        updatedCoveredAmountjTextField.setVisible(false);
        insurerjLabel.setVisible(false);
        coveredAmountjLabel.setVisible(false);
    }//GEN-LAST:event_nojRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balancejTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel coveredAmountjLabel;
    private javax.swing.JTextField coveredAmountjTextField;
    private javax.swing.JTextField currentBalancejTextField;
    private javax.swing.JComboBox insurerjComboBox;
    private javax.swing.JLabel insurerjLabel;
    private javax.swing.JTextField insurerjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton nojRadioButton;
    private javax.swing.JTextField updatedCoveredAmountjTextField;
    private javax.swing.JButton updatejButton;
    private javax.swing.JRadioButton yesjRadioButton;
    // End of variables declaration//GEN-END:variables
}
