/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Distributor;

import Business.Vaccine.VaccineProduct;
import Business.Warehouse.Warehouse;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ViewInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInventoryJPanel
     */
    private JPanel workContainer;
    private Warehouse warehouse;
    
    public ViewInventoryJPanel(JPanel workContainer, Warehouse warehouse ) {
        initComponents();
        this.workContainer = workContainer;
        this.warehouse = warehouse;
        warehouseID.setText(String.valueOf(warehouse.getId()));
        locationjTextField.setText(String.valueOf(warehouse.getLocation()));
        populateTable();
        temperaturejTextField.setText(String.valueOf(warehouse.getTemperature()));
    }
    
    private void populateTable(){
        
         DefaultTableModel model = (DefaultTableModel) inventoryjTable.getModel();
        model.setRowCount(0);
        
        for(VaccineProduct product : warehouse.getVaccineInventoryList())
        {
            Object[] row = new Object[10];
            row[0] = product.getVaccineDefinition().getVaccineCode();
            row[1] = product.getVaccineDefinition().getVaccineName();
            row[2] = product.getManufacturerName();
            row[3] = product.getVaccineId();
            row[4] = product.getBatchId();
            row[5] = product.getVaccinePrice();
            row[6] = product.getAvailablity();
            row[7] = String.valueOf(product.getMinOperatingTemp()+ " - " +product.getMaxOperatingTemp());
            row[8] = product.getManufactureDate();
            row[9] = product.getDateOfExpiry();
            
            model.addRow(row);
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        warehouseID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        locationjTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryjTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        backJButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        temperaturejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        newtemperaturejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        setTemperaturejButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Inventory");

        jLabel2.setText("Warehouse ID:");

        warehouseID.setEnabled(false);

        jLabel3.setText("Location:");

        locationjTextField.setEnabled(false);

        inventoryjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Brand", "Vaccine id", "Batch ID", "Price", "Quantity", "Temperature Range", "manufacture date", "expiry date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        inventoryjTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(inventoryjTable);

        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Warehouse Temperature:");

        temperaturejTextField.setEnabled(false);

        jLabel5.setText("Set Warehouse Temperature:");

        jLabel6.setText("Temperature:");

        jLabel7.setText("degrees Centigrate");

        setTemperaturejButton.setText("Set Temperature");
        setTemperaturejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTemperaturejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(warehouseID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(locationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(temperaturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(setTemperaturejButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backJButton2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(newtemperaturejTextField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(warehouseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(locationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(temperaturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(newtemperaturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setTemperaturejButton)
                .addGap(18, 18, 18)
                .addComponent(backJButton2)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void setTemperaturejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTemperaturejButtonActionPerformed
        // TODO add your handling code here:
        
        try{
            double temperature = Double.parseDouble(newtemperaturejTextField.getText());
            
            //check if the temp is suitable for vaccines
            for(VaccineProduct product : warehouse.getVaccineInventoryList())
        {
            double minTemp = product.getMinOperatingTemp();
            double maxTemp = product.getMaxOperatingTemp();
            
            if(temperature < minTemp || temperature > maxTemp)
            {
                String msg = "Temperature not suitable for "+product.getVaccineDefinition().getVaccineName()+" temperature range should be "+minTemp+" - "+maxTemp;
                JOptionPane.showMessageDialog(null, msg);
            return;
            }
            
            warehouse.setTemperature(temperature);
            temperaturejTextField.setText(String.valueOf(warehouse.getTemperature()));
            
            
            
        }
            
            
            
            
            
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter numeric values for temperature");
            return;
        }
        
        
    }//GEN-LAST:event_setTemperaturejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton2;
    private javax.swing.JTable inventoryjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField locationjTextField;
    private javax.swing.JTextField newtemperaturejTextField;
    private javax.swing.JButton setTemperaturejButton;
    private javax.swing.JTextField temperaturejTextField;
    private javax.swing.JTextField warehouseID;
    // End of variables declaration//GEN-END:variables
}
