/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.PublicHealthDepartment;

import Business.Business;
import Business.Enterprise.PublicHealthDepartment;
import Business.Network.StateNetwork;
import Business.Order.OrderItem;
import Business.Organization.CDCOrganization;
import Business.Organization.Organization;
import Business.Organization.PHDImmunizationOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ProviderVaccineOrderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ViewDetailsOfOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsOfOrderJPanel
     */
    private JPanel workContainer;
    private UserAccount userAccount;
    private PublicHealthDepartment enterprise;
    private PHDImmunizationOrganization phdOrg;
    private Business business;
    private StateNetwork state;
    private ProviderVaccineOrderWorkRequest request;
    
    public ViewDetailsOfOrderJPanel(JPanel workContainer, UserAccount userAccount, PublicHealthDepartment enterprise,PHDImmunizationOrganization phdOrg, StateNetwork state,Business business, ProviderVaccineOrderWorkRequest request) {
        initComponents();
        this.workContainer = workContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.phdOrg = phdOrg;
        this.business = business;
        this.state = state;
        this.request = request;
        orderNumberjTextField.setText(String.valueOf(request.getVaccineOrder().getOrderNumber()));
        displayContractDetails();
        populateTable();
        
    }
    
    private void displayContractDetails(){
        
        if(request.isBimonthlyContract())
            contractDetailsjTextField.setText("Bimonthly");
        if(request.isMonthlyContract())
            contractDetailsjTextField.setText("Monthly");
        if(request.isAdhocRequest())
            contractDetailsjTextField.setText("Adhoc");
        
    }
    
    private void populateTable(){
        
         int rowCount = vaccinejTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)vaccinejTable.getModel();
        
        for(int i=rowCount-1 ; i>=0; i--){
            dtm.removeRow(i);
        }
        
        for(OrderItem oi: request.getVaccineOrder().getOrderList())
        {
            Object[] row = new Object[11];
            
                row[0] = oi.getVaccineProduct();
                row[1] = oi;
                row[2] = oi.getVaccineProduct().getVaccineId();
                row[3] = oi.getVaccineProduct().getBatchId();
                row[4] = oi.getVaccineProduct().getVaccinePrice();
                row[5] = String.valueOf(oi.getVaccineProduct().getMinOperatingTemp()+ " - " +oi.getVaccineProduct().getMaxOperatingTemp());
                row[6] = oi.getQuantity();
                row[7] = oi.getVaccineProduct().getManufactureDate();
                row[8] = oi.getVaccineProduct().getDateOfExpiry();
                row[9] = oi.getVaccineProduct().getVaccinePrice()*oi.getQuantity();
                row[10] = oi.getVaccineProduct().getVaccineDefinition().isFederalFunded() ? "Federal" : oi.getVaccineProduct().getVaccineDefinition().isVaccineFundedByMentionedState(state)? " State" : "Not Funded";
                dtm.addRow(row);
                
            
            
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        orderNumberjTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        vaccinejTable = new javax.swing.JTable();
        approveOrderjButton = new javax.swing.JButton();
        backJButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        contractDetailsjTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order Details");

        jLabel2.setText("Order Number:");

        orderNumberjTextField.setEnabled(false);
        orderNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNumberjTextFieldActionPerformed(evt);
            }
        });

        vaccinejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Vaccine id", "Lot Number", "Price", "Temperature Range", "Quantity", "manufacture date", "expiry date", "Amount", "Funded?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vaccinejTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(vaccinejTable);

        approveOrderjButton.setText("Approve Order");
        approveOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveOrderjButtonActionPerformed(evt);
            }
        });

        backJButton2.setText("<< Back");
        backJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Contract Details:");

        contractDetailsjTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(contractDetailsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(approveOrderjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(orderNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(contractDetailsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveOrderjButton)
                    .addComponent(backJButton2))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNumberjTextFieldActionPerformed

    private void backJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton2ActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_backJButton2ActionPerformed

    private void approveOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveOrderjButtonActionPerformed
        // TODO add your handling code here:
        //check if its already approved!
        if(request.getStatus().equalsIgnoreCase("PHD Approved") || request.getStatus().equalsIgnoreCase("Shipped") || request.getStatus().equalsIgnoreCase("CDC Approved") )
        {
             JOptionPane.showMessageDialog(null, "Order already approved!");
             return;
        }
        
        //fetch the cdc org and insert the request into its workQueue
        
        CDCOrganization cdcOrg = null;
        for(Organization org: business.getCdc().getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof CDCOrganization)
            {
                org.getWorkQueue().addWorkRequest(request);
            }
        }
        
        
        
        
        
        request.setApprovedByPHD(true);
        request.setPhdApprovedBy(userAccount);
        request.setStatus("PHD Approved");
        request.setRequestState(state);
        
        JOptionPane.showMessageDialog(null, "Order Sent to CDC!");
               
        
        
        
    }//GEN-LAST:event_approveOrderjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveOrderjButton;
    private javax.swing.JButton backJButton2;
    private javax.swing.JTextField contractDetailsjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField orderNumberjTextField;
    private javax.swing.JTable vaccinejTable;
    // End of variables declaration//GEN-END:variables
}
