/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CDC;

import Business.Business;
import Business.NationalEnterprise.CDC;
import Business.NationalEnterprise.Distributor;
import Business.NationalEnterprise.Manufacturer;
import Business.Organization.CDCOrganization;
import Business.Organization.DistributorOrganization;
import Business.Organization.ManufactureOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.VaccineProduct;
import Business.Warehouse.Warehouse;
import Business.WorkQueue.RecallRequest;
import Business.WorkQueue.VaccineOrderWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.Distributor.*;
import UserInterface.Manufacture.*;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ManageRecallRequestsCDCJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRecallRequestsJPanel
     */
    private JPanel workContainer;
    private CDC cdcEnterprise;
    private UserAccount userAccount;
    private Business business;
    
    public ManageRecallRequestsCDCJPanel(JPanel workContainer, CDC cdcEnterprise, UserAccount userAccount, Business business) {
        initComponents();
        this.workContainer = workContainer;
        this.cdcEnterprise = cdcEnterprise;
        this.userAccount = userAccount;
        this.business = business;
        populateOrderTable();
    }
    
    private void populateOrderTable(){
        
         DefaultTableModel model = (DefaultTableModel) workRequestjTable.getModel();
        model.setRowCount(0);
         CDCOrganization cdcOrg = null;
         
        for(Organization org : cdcEnterprise.getOrganizationDirectory().getOrganizationList())
        {   if(org instanceof CDCOrganization)
        {   cdcOrg = (CDCOrganization)org;
            for(WorkRequest workRequest : cdcOrg.getWorkQueue().getWorkRequestList())
            {   if(workRequest instanceof RecallRequest)
            {RecallRequest recallRequest = (RecallRequest)workRequest;
                
                Object[] row = new Object[11];
            
                row[0] = recallRequest;
                row[1] = recallRequest.getAdVaccine();
                row[2] = recallRequest.getAdVaccine().getVaccineProduct().getBatchId();
                row[3] = recallRequest.getRequestDate();
                row[4] = recallRequest.getSender();
                row[5] = recallRequest.getStatus();
                row[6] = recallRequest.getReceiver();
                row[7] = recallRequest.getResolveDate();
                
                
                row[8] = recallRequest.getDistributorStatus();
                row[9] = recallRequest.getDistributorUserAccount();
                row[10] = recallRequest.getDistributorRemoveDate();
                
                model.addRow(row);
                
            }
            }
        }
        
        
        
        
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestjTable = new javax.swing.JTable();
        refreshjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Recall Requests");

        workRequestjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Batch ID", "Request Date", "Sender", "M Status", "M Removed By", "M Removed On", "D Status", "D Removed By", "D Removed On"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        workRequestjTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(workRequestjTable);

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshjButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshjButton)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        // TODO add your handling code here:
        populateOrderTable();
    }//GEN-LAST:event_refreshjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JTable workRequestjTable;
    // End of variables declaration//GEN-END:variables
}
