/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.CDC;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.NationalEnterprise.Manufacturer;
import Business.Organization.CDCOrganization;
import Business.Organization.DistributorOrganization;
import Business.Organization.ManufactureOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Vaccine.AdministeredVaccine;
import Business.WorkQueue.RecallRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.Patient.*;
import UserInterface.Provider.*;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vaibhav
 */
public class ProviderViewSideEffectsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReportSideEffectsJPanel
     */
    private JPanel workContainer;
    private AdministeredVaccine vaccine;
    private Enterprise enterprise;
    private Business business;
    private UserAccount userAccount;
    
    public ProviderViewSideEffectsJPanel(JPanel workContainer,AdministeredVaccine vaccine, Enterprise enterprise, Business business, UserAccount userAccount ) {
        initComponents();
        this.workContainer = workContainer;
        this.vaccine = vaccine;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = userAccount;
        vaccineCodejTextField.setText(vaccine.getVaccineProduct().getVaccineDefinition().getVaccineCode());
        vaccineNamejTextField.setText(vaccine.getVaccineProduct().getVaccineDefinition().getVaccineName());
        brandjTextField.setText(vaccine.getVaccineProduct().getManufacturerName());
        batchIDjTextField.setText(vaccine.getVaccineProduct().getBatchId());
        datejTextField.setText(String.valueOf(vaccine.getDate()));
        siteRoutejTextField.setText(vaccine.getSiteRoute());
        doseNumberjTextField.setText(String.valueOf(vaccine.getDoseNumber()));
        if(vaccine.getReasonForFailure() != null)
        {
            sideEffectsjTextArea.setText(vaccine.getReasonForFailure());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vaccineCodejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        vaccineNamejTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        brandjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        batchIDjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        datejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        siteRoutejTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        doseNumberjTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sideEffectsjTextArea = new javax.swing.JTextArea();
        backJButton3 = new javax.swing.JButton();
        makeARecallRequestjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Side Effects");

        jLabel2.setText("Vaccine Details:");

        jLabel3.setText("Vaccine Code:");

        vaccineCodejTextField.setEnabled(false);

        jLabel4.setText("Vaccine Name:");

        vaccineNamejTextField.setEnabled(false);

        jLabel5.setText("Brand:");

        brandjTextField.setEnabled(false);

        jLabel6.setText("Batch ID:");

        batchIDjTextField.setEnabled(false);

        jLabel7.setText("Date:");

        datejTextField.setEnabled(false);

        jLabel8.setText("Site/Route:");

        siteRoutejTextField.setEnabled(false);

        jLabel9.setText("Dose Number:");

        doseNumberjTextField.setEnabled(false);

        jLabel10.setText("View Side Effects:");

        sideEffectsjTextArea.setColumns(20);
        sideEffectsjTextArea.setRows(5);
        sideEffectsjTextArea.setEnabled(false);
        jScrollPane1.setViewportView(sideEffectsjTextArea);

        backJButton3.setText("<< Back");
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });

        makeARecallRequestjButton.setText("Make a Recall Request");
        makeARecallRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeARecallRequestjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doseNumberjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vaccineCodejTextField)
                                            .addComponent(brandjTextField)
                                            .addComponent(datejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(vaccineNamejTextField)
                                            .addComponent(batchIDjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(siteRoutejTextField))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(backJButton3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(makeARecallRequestjButton))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(vaccineCodejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(vaccineNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(brandjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(batchIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(datejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(siteRoutejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(doseNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backJButton3)
                    .addComponent(makeARecallRequestjButton))
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void makeARecallRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeARecallRequestjButtonActionPerformed
        // TODO add your handling code here:
        //check if the administered vaccine status is fail
        if(vaccine.getInjectionStatus().equalsIgnoreCase("Success"))
        {
            JOptionPane.showMessageDialog(null, "Vaccine status is success! Only Failed vaccine can be recalled");
            return;
        }
        // Check if the vaccine has been recalled previously
        
        String vaccineName = vaccine.getVaccineProduct().getVaccineDefinition().getVaccineName();
        String batchId = vaccine.getVaccineProduct().getBatchId();
        
        for(Organization org : business.getCdc().getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof CDCOrganization)
            {
                CDCOrganization cdcOrg = (CDCOrganization)org;
                for(WorkRequest wr: cdcOrg.getWorkQueue().getWorkRequestList())
                {
                    if(wr instanceof RecallRequest)
                    {
                        RecallRequest rwr = (RecallRequest)wr;
                        if(rwr.getAdVaccine().getVaccineProduct().getBatchId().equalsIgnoreCase(batchId) && rwr.getAdVaccine().getVaccineProduct().getVaccineDefinition().getVaccineName().equalsIgnoreCase(vaccineName))
                        {
                            JOptionPane.showMessageDialog(null, "Vaccine already Recalled!");
            return;
                            
                        }
                    }
                }
            }
            
            }
        
        
        
        
        
        
        //make a recall Request
        RecallRequest recallRequest = new RecallRequest();
        recallRequest.setRequestDate(new Date());
        recallRequest.setSender(userAccount);
        recallRequest.setStatus("New");
        recallRequest.setAdVaccine(vaccine);
        recallRequest.setDistributorStatus("New");
        
        //add it to own work request
        for(Organization org : business.getCdc().getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof CDCOrganization)
            {
                CDCOrganization cdcOrg = (CDCOrganization)org;
                cdcOrg.getWorkQueue().addWorkRequest(recallRequest);
            }
            
            }
        
        
        //send it to Distributor 
        
        for(Organization org : business.getDistributor().getOrganizationDirectory().getOrganizationList())
        {
            if(org instanceof DistributorOrganization)
            {
                DistributorOrganization distOrg = (DistributorOrganization)org;
                distOrg.getWorkQueue().addWorkRequest(recallRequest);
                
                
            }
        }
        
        
        
        //send it to Manufacturer
        
        //get the manufacturer
        String manufacturerName = vaccine.getVaccineProduct().getManufacturerName();
        for (Manufacturer manuf : business.getManufacturerDirectory().getManufacturerList())
        {
            if(manuf.getName().equalsIgnoreCase(manufacturerName))
            {
                for(Organization org : manuf.getOrganizationDirectory().getOrganizationList())
                {
                    if(org instanceof ManufactureOrganization)
                    {
                        ManufactureOrganization manufOrg = (ManufactureOrganization) org;
                        manufOrg.getWorkQueue().addWorkRequest(recallRequest);
                    }
                }
            }
            
        }
        
        
        JOptionPane.showMessageDialog(null, "Recall Request sent!");
        
        
        
    }//GEN-LAST:event_makeARecallRequestjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton3;
    private javax.swing.JTextField batchIDjTextField;
    private javax.swing.JTextField brandjTextField;
    private javax.swing.JTextField datejTextField;
    private javax.swing.JTextField doseNumberjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton makeARecallRequestjButton;
    private javax.swing.JTextArea sideEffectsjTextArea;
    private javax.swing.JTextField siteRoutejTextField;
    private javax.swing.JTextField vaccineCodejTextField;
    private javax.swing.JTextField vaccineNamejTextField;
    // End of variables declaration//GEN-END:variables
}
