/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdmin;

import Business.Business;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Vaibhav
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    
      private JPanel workContainer;
    private Business business;
    public ManageUserAccountJPanel(JPanel workContainer, Business business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageCDCUserAccountjButton = new javax.swing.JButton();
        manageDistributorjButton = new javax.swing.JButton();
        manageProviderAdminjButton = new javax.swing.JButton();
        managePHDaccountsjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage User Account");

        manageCDCUserAccountjButton.setText("Manage CDC Admins >>");
        manageCDCUserAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCDCUserAccountjButtonActionPerformed(evt);
            }
        });

        manageDistributorjButton.setText("Manage Distributor Admins >>");
        manageDistributorjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDistributorjButtonActionPerformed(evt);
            }
        });

        manageProviderAdminjButton.setText("Manage Provider Admins >>");
        manageProviderAdminjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProviderAdminjButtonActionPerformed(evt);
            }
        });

        managePHDaccountsjButton.setText("Manage Public Health Dept Admins >>");
        managePHDaccountsjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePHDaccountsjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageCDCUserAccountjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDistributorjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageProviderAdminjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(managePHDaccountsjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manageCDCUserAccountjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageDistributorjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(managePHDaccountsjButton)
                .addGap(12, 12, 12)
                .addComponent(manageProviderAdminjButton)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProviderAdminjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProviderAdminjButtonActionPerformed
        // TODO add your handling code here:
        ManageProviderUserAccountJPanel panel = new ManageProviderUserAccountJPanel(workContainer, business);
        workContainer.add("ManageProviderUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_manageProviderAdminjButtonActionPerformed

    private void managePHDaccountsjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePHDaccountsjButtonActionPerformed
        // TODO add your handling code here:
        ManagePublicHealthDepartmentUserAccountJPanel panel = new ManagePublicHealthDepartmentUserAccountJPanel(workContainer, business);
        workContainer.add("ManagePublicHealthDepartmentUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_managePHDaccountsjButtonActionPerformed

    private void manageCDCUserAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCDCUserAccountjButtonActionPerformed
        // TODO add your handling code here:
         ManageCDCUserAccountJPanel panel = new ManageCDCUserAccountJPanel(workContainer, business);
        workContainer.add("ManageCDCUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_manageCDCUserAccountjButtonActionPerformed

    private void manageDistributorjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDistributorjButtonActionPerformed
        // TODO add your handling code here:
        ManageDistributorUserAccountJPanel panel = new ManageDistributorUserAccountJPanel(workContainer, business);
        workContainer.add("ManageDistributorUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_manageDistributorjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCDCUserAccountjButton;
    private javax.swing.JButton manageDistributorjButton;
    private javax.swing.JButton managePHDaccountsjButton;
    private javax.swing.JButton manageProviderAdminjButton;
    // End of variables declaration//GEN-END:variables
}
