/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdmin;

import Business.Business;
import Business.NationalEnterprise.Manufacturer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ManageManufacturersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageManufacturersJPanel
     */
     private JPanel workContainer;
    private Business business;
    
    public ManageManufacturersJPanel(JPanel workContainer, Business business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
        populateTable();
        
    }
    
    private void populateTable(){
        int rowCount = manufacturerJTable.getRowCount();
         DefaultTableModel dtm = (DefaultTableModel)manufacturerJTable.getModel();
        
        //delete rows
        for(int i=rowCount-1 ; i>=0; i--){
            dtm.removeRow(i);
        }
        
        //populate the table
        for (Manufacturer manufacturer: business.getManufacturerDirectory().getManufacturerList()){
            Object[] row = new Object[1];
            row[0]=manufacturer;
            
            dtm.addRow(row);
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        manufacturerJTable = new javax.swing.JTable();
        createManufactureAdminJButton = new javax.swing.JButton();
        removeManufacturerJButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        manufacturerJTextField = new javax.swing.JTextField();
        addManufacturerJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Manufacturers");

        manufacturerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manufacturerJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(manufacturerJTable);
        if (manufacturerJTable.getColumnModel().getColumnCount() > 0) {
            manufacturerJTable.getColumnModel().getColumn(0).setResizable(false);
        }

        createManufactureAdminJButton.setText("Create Manufacturer Admin >>");
        createManufactureAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createManufactureAdminJButtonActionPerformed(evt);
            }
        });

        removeManufacturerJButton.setText("Remove Manufacturer");
        removeManufacturerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeManufacturerJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Add New Manufacturer: ");

        jLabel3.setText("Manufacturer Name: ");

        addManufacturerJButton.setText("Add Manufacturer");
        addManufacturerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addManufacturerJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(removeManufacturerJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createManufactureAdminJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(manufacturerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addManufacturerJButton))
                            .addComponent(backJButton))
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createManufactureAdminJButton)
                    .addComponent(removeManufacturerJButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manufacturerJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addManufacturerJButton))
                .addGap(18, 18, 18)
                .addComponent(backJButton)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addManufacturerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addManufacturerJButtonActionPerformed
        // TODO add your handling code here:
        String name = manufacturerJTextField.getText();
        if(name.trim().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter a Manufacturer name!");
            return;
        }
        
        for(Manufacturer man: business.getManufacturerDirectory().getManufacturerList())
        {
            if(man.getName().equalsIgnoreCase(name))
            {
                JOptionPane.showMessageDialog(null, "Manufacturer exists!");
            return;
            }
        }
        
        
        business.getManufacturerDirectory().addNewManufacturer(name);
        
        populateTable();
        
        
    }//GEN-LAST:event_addManufacturerJButtonActionPerformed

    private void removeManufacturerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeManufacturerJButtonActionPerformed
        // TODO add your handling code here:
        
        int row = manufacturerJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Manufacturer from table");
            return;
        }
        
        Manufacturer manufacturer =(Manufacturer) manufacturerJTable.getValueAt(row, 0);
        business.getManufacturerDirectory().removeManufacturer(manufacturer);
        populateTable();
        
        
    }//GEN-LAST:event_removeManufacturerJButtonActionPerformed

    private void createManufactureAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createManufactureAdminJButtonActionPerformed
        // TODO add your handling code here:
        int row = manufacturerJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Manufacturer from table");
            return;
        }
        
        Manufacturer manufacturer =(Manufacturer) manufacturerJTable.getValueAt(row, 0);
        
        ManageManufactureAdminUserAccountJPanel panel = new ManageManufactureAdminUserAccountJPanel(workContainer, manufacturer, business );
        workContainer.add("ManageManufactureAdminUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
        
    }//GEN-LAST:event_createManufactureAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addManufacturerJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createManufactureAdminJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable manufacturerJTable;
    private javax.swing.JTextField manufacturerJTextField;
    private javax.swing.JButton removeManufacturerJButton;
    // End of variables declaration//GEN-END:variables
}
