/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdmin;

import Business.Business;
import Business.Vaccine.Vaccine;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ManageVaccineCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageVaccineCatalogJPanel
     */
     private JPanel workContainer;
    private Business business;
    
    public ManageVaccineCatalogJPanel(JPanel workContainer, Business business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
        populateTable();
    }
    
    private void populateTable(){
        
        DefaultTableModel model = (DefaultTableModel) vaccineJTable.getModel();
        model.setRowCount(0);
        
        for(Vaccine vaccine : business.getVaccineCatalog().getVaccineCatalog())
        {
            Object[] row = new Object[4];
            row[0] = vaccine;
            row[1] = vaccine.getVaccineName();
            row[2] = vaccine.getDateOnVIS();
            row[3] = vaccine.getLastUpdatedVIS();
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vaccineJTable = new javax.swing.JTable();
        editVaccineJButton = new javax.swing.JButton();
        addVaccineJButton = new javax.swing.JButton();
        removeVaccineJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        refreshjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Vaccine Catalog");

        vaccineJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Date on VIS", "Last updated"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vaccineJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(vaccineJTable);
        if (vaccineJTable.getColumnModel().getColumnCount() > 0) {
            vaccineJTable.getColumnModel().getColumn(0).setResizable(false);
            vaccineJTable.getColumnModel().getColumn(1).setResizable(false);
            vaccineJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        editVaccineJButton.setText("Edit Vaccine Info");
        editVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editVaccineJButtonActionPerformed(evt);
            }
        });

        addVaccineJButton.setText("Add Vaccine >>");
        addVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineJButtonActionPerformed(evt);
            }
        });

        removeVaccineJButton.setText("Remove Vaccine");
        removeVaccineJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeVaccineJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeVaccineJButton)
                        .addGap(47, 47, 47)
                        .addComponent(editVaccineJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addVaccineJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(refreshjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(refreshjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editVaccineJButton)
                    .addComponent(addVaccineJButton)
                    .addComponent(removeVaccineJButton))
                .addGap(26, 26, 26)
                .addComponent(backJButton)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void removeVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeVaccineJButtonActionPerformed
        // TODO add your handling code here:
        
         int row = vaccineJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Vaccine from table");
            return;
        }
        
        Vaccine vaccine = (Vaccine)vaccineJTable.getValueAt(row, 0);
        business.getVaccineCatalog().removeVaccineDefinition(vaccine);
        populateTable();
        
    }//GEN-LAST:event_removeVaccineJButtonActionPerformed

    private void addVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineJButtonActionPerformed
        // TODO add your handling code here:
        
       
        
        
        AddNewVaccineInfoJPanel panel = new AddNewVaccineInfoJPanel(workContainer, business);
        workContainer.add("AddNewVaccineInfoJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_addVaccineJButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshjButtonActionPerformed

    private void editVaccineJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editVaccineJButtonActionPerformed
        // TODO add your handling code here:
        int row = vaccineJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Vaccine from table");
            return;
        }
        Vaccine vaccine = (Vaccine)vaccineJTable.getValueAt(row, 0);
        
                
        EditVaccineInfoJPanel panel = new EditVaccineInfoJPanel(workContainer, vaccine);
        workContainer.add("EditVaccineInfoJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
    }//GEN-LAST:event_editVaccineJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton editVaccineJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JButton removeVaccineJButton;
    private javax.swing.JTable vaccineJTable;
    // End of variables declaration//GEN-END:variables
}
