/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.Provider;

import Business.Network.StateNetwork;
import Business.Order.OrderItem;
import Business.Organization.Organization;
import Business.Organization.PHDImmunizationOrganization;
import Business.WorkQueue.ProviderVaccineOrderWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ViewDetailsOfSatelliteClinicOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailsOfPlacedOrderJPanel
     */
    private JPanel workContainer;
    private ProviderVaccineOrderWorkRequest request;
    private StateNetwork state;
    
    public ViewDetailsOfSatelliteClinicOrderJPanel(JPanel workContainer, ProviderVaccineOrderWorkRequest request, StateNetwork state) {
        initComponents();
        this.workContainer = workContainer;
        this.request = request;
        this.state = state;
        displayContractDetails();
        calculateTotalCostOfOrder();
        orderjTextField.setText(String.valueOf(request.getVaccineOrder().getOrderNumber()));
        populateOrderTable();
    }
    
    private void displayContractDetails(){
        
        if(request.isBimonthlyContract())
            contractDetailsjTextField.setText("Bimonthly");
        if(request.isMonthlyContract())
            contractDetailsjTextField.setText("Monthly");
        if(request.isAdhocRequest())
            contractDetailsjTextField.setText("Adhoc");
        
    }
    
    private void calculateTotalCostOfOrder(){
        
        double total = 0;
        for(OrderItem oi : request.getVaccineOrder().getOrderList())
        {
            total = total + (oi.getVaccineProduct().getVaccinePrice()*oi.getQuantity());
        }
        totalCostjTextField.setText(String.valueOf(total));
    }
    
    private void populateOrderTable(){
        
         int rowCount = orderjTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)orderjTable.getModel();
        
        for(int i=rowCount-1 ; i>=0; i--){
            dtm.removeRow(i);
        }
        
        for(OrderItem oi: request.getVaccineOrder().getOrderList())
        {
            Object[] row = new Object[12];
            
                row[0] = oi.getVaccineProduct();
                row[1] = oi;
                row[2] = oi.getVaccineProduct().getManufacturerName();
                row[3] = oi.getVaccineProduct().getVaccineId();
                row[4] = oi.getVaccineProduct().getBatchId();
                
                row[5] = oi.getVaccineProduct().getVaccinePrice();
                row[6] = String.valueOf(oi.getVaccineProduct().getMinOperatingTemp()+ " - " +oi.getVaccineProduct().getMaxOperatingTemp());
                row[7] = oi.getQuantity();
                row[8] = oi.getVaccineProduct().getManufactureDate();
                row[9] = oi.getVaccineProduct().getDateOfExpiry();
                row[10] = oi.getVaccineProduct().getVaccinePrice()*oi.getQuantity();
                row[11] = oi.getVaccineProduct().getVaccineDefinition().isFederalFunded() ? "Federal" : oi.getVaccineProduct().getVaccineDefinition().isStateFunded()? " State" : "Not Funded";
               
                dtm.addRow(row);
            
            
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        contractDetailsjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalCostjTextField = new javax.swing.JTextField();
        orderjTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderjTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        backJButton3 = new javax.swing.JButton();
        forwardOrderjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Details of Placed Order by Satellite Clinic");

        contractDetailsjTextField.setEnabled(false);

        jLabel3.setText("Order Particulars:");

        jLabel5.setText("Total Cost of the Order:");

        jLabel2.setText("Order Number:");

        totalCostjTextField.setEnabled(false);

        orderjTextField.setEnabled(false);

        orderjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Brand", "Vaccine id", "Batch ID", "Price", "Temperature Range", "Quantity", "manufacture date", "expiry date", "Amount", "Funded?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        orderjTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(orderjTable);

        jLabel6.setText("Contract :");

        backJButton3.setText("<< Back");
        backJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton3ActionPerformed(evt);
            }
        });

        forwardOrderjButton.setText("Forward the Order to PHD");
        forwardOrderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardOrderjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalCostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(contractDetailsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(forwardOrderjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(contractDetailsjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(totalCostjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(orderjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton3)
                    .addComponent(forwardOrderjButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton3ActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_backJButton3ActionPerformed

    private void forwardOrderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardOrderjButtonActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equalsIgnoreCase("FWD to PHD") || request.getStatus().equalsIgnoreCase("Shipped") || request.getStatus().equalsIgnoreCase("Stored"))
        {
            JOptionPane.showMessageDialog(null, "Order already forwarded to PHD!");
            return;
        }
        
        
        for(Organization org: state.getPublicHealthDepartment().getOrganizationDirectory().getOrganizationList())
                {
                    if(org instanceof PHDImmunizationOrganization)
                    {
                        org.getWorkQueue().addWorkRequest(request);
                    }
                }
        request.setStatus("FWD to PHD");
        
        JOptionPane.showMessageDialog(null, "Order forwarded to PHD!");
    }//GEN-LAST:event_forwardOrderjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton3;
    private javax.swing.JTextField contractDetailsjTextField;
    private javax.swing.JButton forwardOrderjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderjTable;
    private javax.swing.JTextField orderjTextField;
    private javax.swing.JTextField totalCostjTextField;
    // End of variables declaration//GEN-END:variables
}
