/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PublicHealthDepartment;
import Business.NationalEnterprise.CDC;
import Business.NationalEnterprise.Distributor;
import Business.NationalEnterprise.Manufacturer;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Organization.SatelliteClinicOrganization;
import Business.Person.Patient;
import Business.Person.Person;
import Business.Role.Role.RoleType;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Vaibhav
 */




public class CreatePersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEmployeeJPanel
     */
    private JPanel workContainer;
    private Enterprise enterprise;
    
    public CreatePersonJPanel(JPanel workContainer, Enterprise enterprise) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        departmentjComboBox.removeAllItems();
        populateDepartmentComboBox();
        satelliteClinicjLabel.setVisible(false);
            satelliteClinicjTextField.setVisible(false);
        if(enterprise instanceof HospitalEnterprise)
        {
            satelliteClinicjLabel.setVisible(true);
            satelliteClinicjTextField.setVisible(true);
        }
        
        
    }
    
    public void populateDepartmentComboBox(){
        
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            departmentjComboBox.addItem(org);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstNamejTextField = new javax.swing.JTextField();
        lastNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email1jTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email2jTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phonejTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dateOfBirthjDateChooser = new com.toedter.calendar.JDateChooser();
        addEmployeejButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        departmentjComboBox = new javax.swing.JComboBox();
        satelliteClinicjLabel = new javax.swing.JLabel();
        satelliteClinicjTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Person");

        jLabel2.setText("First Name: ");

        firstNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNamejTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Last Name: ");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("email:");

        jLabel5.setText("@");

        jLabel6.setText("Phone:");

        jLabel7.setText("Date of Birth:");

        addEmployeejButton.setText("Add Person");
        addEmployeejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeejButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Department:");

        departmentjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        departmentjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentjComboBoxActionPerformed(evt);
            }
        });

        satelliteClinicjLabel.setText("Satellite Clinic Name:");

        satelliteClinicjTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)))
                            .addComponent(jLabel7)
                            .addComponent(satelliteClinicjLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addEmployeejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNamejTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(email1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email2jTextField))
                            .addComponent(phonejTextField)
                            .addComponent(dateOfBirthjDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(departmentjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(satelliteClinicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(firstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(email2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(phonejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(dateOfBirthjDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(departmentjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(satelliteClinicjLabel)
                    .addComponent(satelliteClinicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEmployeejButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(backJButton)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNamejTextFieldActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void addEmployeejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeejButtonActionPerformed
        // TODO add your handling code here:
        try{
         long phone = Long.parseLong(phonejTextField.getText());
         
        String firstName = firstNamejTextField.getText();
        if(firstName.trim().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter first Name!");
            return;
        }
        
        String lastName = lastNamejTextField.getText();
        if(lastName.trim().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter last Name!");
            return;
        }
        String email = email1jTextField.getText()+"@"+email2jTextField.getText();
       
        Date dob = dateOfBirthjDateChooser.getDate();
        Organization org = (Organization)departmentjComboBox.getSelectedItem();
        Person person = null;
        Patient patient = null;
        if(enterprise instanceof CDC)
        { person = org.getPersonDirectory().createPerson(firstName, lastName, RoleType.CDCEmployee);
            System.out.println("NEW PERSON FOR CDC : " + person.toString());
        }
         if(enterprise instanceof Manufacturer)
        { person = org.getPersonDirectory().createPerson(firstName, lastName, RoleType.Manufacturer);
        }
         if(enterprise instanceof Distributor)
        { person = org.getPersonDirectory().createPerson(firstName, lastName, RoleType.Distributor);
        }
         if(enterprise instanceof PublicHealthDepartment)
        { person = org.getPersonDirectory().createPerson(firstName, lastName, RoleType.PublicHealthDepartment);
        }
         if(enterprise instanceof HospitalEnterprise)
         {
             if(org instanceof HospitalOrganization)
            { person = org.getPersonDirectory().createPerson(firstName, lastName, RoleType.Provider);
            }
             if(org instanceof PatientOrganization)
            { patient = (Patient)org.getPersonDirectory().createPerson(firstName, lastName, RoleType.Patient);
            }
             if(org instanceof SatelliteClinicOrganization)
            { person = org.getPersonDirectory().createPerson(firstName, lastName, RoleType.SatelliteClinicProvider);
            }
         
        
         }
         if(person!=null)
         {person.setDateOfBirth(dob);
         person.setEmail(email);
         person.setPhone(phone);
         }
         if(patient!=null)
         {patient.setDateOfBirth(dob);
         patient.setEmail(email);
         patient.setPhone(phone);
         }
         
         
          JOptionPane.showMessageDialog(null, "Person Added!");
         
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please enter numeric value for phone");
            return;
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_addEmployeejButtonActionPerformed

    private void departmentjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentjComboBoxActionPerformed
        // TODO add your handling code here:
        
        Organization org =(Organization)departmentjComboBox.getSelectedItem();
        if(org ==  null)
        {
            return;
        }
        if(org instanceof SatelliteClinicOrganization)
        {   SatelliteClinicOrganization satOrg = (SatelliteClinicOrganization)org;
            satelliteClinicjTextField.setText(satOrg.getSatelliteClincName());
        }
        else
            return;
        
        
    }//GEN-LAST:event_departmentjComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeejButton;
    private javax.swing.JButton backJButton;
    private com.toedter.calendar.JDateChooser dateOfBirthjDateChooser;
    private javax.swing.JComboBox departmentjComboBox;
    private javax.swing.JTextField email1jTextField;
    private javax.swing.JTextField email2jTextField;
    private javax.swing.JTextField firstNamejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastNamejTextField;
    private javax.swing.JTextField phonejTextField;
    private javax.swing.JLabel satelliteClinicjLabel;
    private javax.swing.JTextField satelliteClinicjTextField;
    // End of variables declaration//GEN-END:variables
}
