/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.EnterpriseAdmin;

import Business.Business;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SatelliteClinicOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vaibhav
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel workContainer;
    private Enterprise enterprise;
    private Business business;
    
    public ManageUserAccountJPanel(JPanel workContainer, Enterprise enterprise , Business business) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }
    
    protected void populateTable(){
        DefaultTableModel model = (DefaultTableModel) userAccountJTable.getModel();

        model.setRowCount(0);
        
            for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[5];
                row[0] = ua.getPerson().getFirstName()+ " "+ua.getPerson().getLastName();
                row[1] = "Enterprise Admin";
                row[2] = ua;
                row[3] = ua.getPassword();
                row[4] = ua.getRole();
                
                ((DefaultTableModel) userAccountJTable.getModel()).addRow(row);
            }
        
        

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[5];
                row[0] = ua.getPerson().getFirstName()+ " "+ua.getPerson().getLastName();
                if(organization instanceof SatelliteClinicOrganization)
            {
                SatelliteClinicOrganization satOrg =(SatelliteClinicOrganization)organization;
                row[1] = satOrg.getSatelliteClincName()+" Satellite Clinic";
            }
                else row[1] = organization;
                row[2] = ua;
                row[3] = ua.getPassword();
                row[4] = ua.getRole();
                
                ((DefaultTableModel) userAccountJTable.getModel()).addRow(row);
            }
        }
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAccountJTable = new javax.swing.JTable();
        createUserjButton = new javax.swing.JButton();
        viewUserAccountjButton = new javax.swing.JButton();
        removeUserjButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage User Accounts");

        userAccountJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Department", "UserName", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userAccountJTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(userAccountJTable);
        if (userAccountJTable.getColumnModel().getColumnCount() > 0) {
            userAccountJTable.getColumnModel().getColumn(0).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(1).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(2).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(3).setResizable(false);
            userAccountJTable.getColumnModel().getColumn(4).setResizable(false);
        }

        createUserjButton.setText("Create New User Account >>");
        createUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserjButtonActionPerformed(evt);
            }
        });

        viewUserAccountjButton.setText("View / Update User Account");
        viewUserAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUserAccountjButtonActionPerformed(evt);
            }
        });

        removeUserjButton.setText("Remove User");
        removeUserjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeUserjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(viewUserAccountjButton)
                        .addGap(67, 67, 67)
                        .addComponent(removeUserjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(createUserjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createUserjButton)
                    .addComponent(viewUserAccountjButton)
                    .addComponent(removeUserjButton))
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserjButtonActionPerformed
        // TODO add your handling code here:
         CreateUserAccountJPanel panel = new CreateUserAccountJPanel(workContainer, enterprise , this, business);
        workContainer.add("CreateUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_createUserjButtonActionPerformed

    private void removeUserjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeUserjButtonActionPerformed
        // TODO add your handling code here:
        int row = userAccountJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a user account from table");
            return;
        }
        Organization org = null;
        
        UserAccount ua = (UserAccount)userAccountJTable.getValueAt(row, 2);
        
        
        if(userAccountJTable.getValueAt(row, 1) instanceof String)
        {
            enterprise.getUserAccountDirectory().removeUserAccount(ua);
        }
        else
        { org = (Organization) userAccountJTable.getValueAt(row, 1);
        
        org.getUserAccountDirectory().removeUserAccount(ua);
        }
        populateTable();
        
    }//GEN-LAST:event_removeUserjButtonActionPerformed

    private void viewUserAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUserAccountjButtonActionPerformed
        // TODO add your handling code here:
        int row = userAccountJTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a user account from table");
            return;
        }
        Organization org = null;
        UserAccount ua = (UserAccount)userAccountJTable.getValueAt(row, 2);
        if((userAccountJTable.getValueAt(row, 1) instanceof String) == false)
        org = (Organization) userAccountJTable.getValueAt(row, 1);
        ViewUserAccountJPanel panel = new ViewUserAccountJPanel(workContainer, enterprise , this, ua, org, business);
        workContainer.add("ViewUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
    }//GEN-LAST:event_viewUserAccountjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUserjButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeUserjButton;
    private javax.swing.JTable userAccountJTable;
    private javax.swing.JButton viewUserAccountjButton;
    // End of variables declaration//GEN-END:variables
}
